title: Masque Works
description: Home of the Masque Cue-Running App
theme: just-the-docs

url: https://lordaine.github.io

color_scheme: dark

aux_links:
  "Masque Stage": https://masquestage.com

footer_content: "Copyright &copy; 2025 Masque Works, LLC."
